### ISSUE TITLE
Add Contributing.md file to help new contributors and make README more attractive

### ISSUE THREAD

**Issue by PeritusDeveloper** [SameerSahu007/discord-uiclone#4]
- Glimpse
<img width="470" alt="image" src="https://user-images.githubusercontent.com/89828000/193902777-c0f09c19-0c9d-469d-a248-34436938b77b.png">

- Adding Contributing.md file
- Adding **Auto-Update Contribution Section** in README.md file wherein all the contributors along with their profile picture can be seen.

**Comment by SameerSahu007** [comment]
looks great feel free to do it.

**Comment by PeritusDeveloper** [comment]
Thanks!
